---
# Organization to pull metrics from
organization: 'worldbank'

# Start date to pull metrics from
since: '2023-01-02'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/org-metrics-dashboard'
